### ISSUE TITLE
Incompatibility With MoreItems (Cracked Orb + "To The Stars" Special)

### ISSUE THREAD

**Issue by KdronTheShadow** [ArcPh1r3/MinerUnearthed#3] opened 2021-08-13 21:50 UTC
With the modded item **_Cracked Orb_** from **_MoreItems_** by **_XoXFaby_** which grants a **_+30% chance per stack to duplicate attacks_**, the miner's special ability **_To The Stars_** becomes unusable due to the insane _duplication_ of projectiles from the ability. 

The reason I am posting this here is that this issue doesn't happen with any other items / attacks paired with the cracked orb unless you have TONS of them (6-10+), so I speculate it is caused from how this attack behaves / deals with individual projectiles as a whole though I could be way off, sorry if this isn't the case!

using bleed stacks from 10 needles and a dps meters I was able to calculate that I had shot over **30,000+ projectiles** in a **single shot** with just **ONE Cracked Orb**, causing my game to hang and then eventually crash. 

I believe it could be one of these two logical conclusions, but as I don't know the inner workings of either mod it's just my best guess.

A) **self duplication of individual projectiles** 
high proc chance on individual projectiles that duplicates it almost endlessly 
_(shoot -> each one then rolls to duplicate -> then each one of the duplicates roll to duplicate -> and so forth)_

B) **whole duplication of the entire attack** 
any individual projectiles that succeeds, duplicates an entire new "To The Stars" causing 30 more projectiles. 
_(shoot 30x -> rolls for any that hit and duplicates the ENTIRE attack again for any that succeed -> shoot 30xNumberThatPassedTheRoll -> and so forth)_

Examples 

_**24,877 bleed stacks in one shot**_ (Look at that **_raw_** base 12 damage lol)
![20210813144210_1](https://user-images.githubusercontent.com/88908714/129421539-e298f075-d74b-41ab-9730-001936c15e6a.jpg)

**_DPS from said shot next frame_**
![20210813144317_1](https://user-images.githubusercontent.com/88908714/129421573-04fcd16e-678d-42a8-bd55-ec88cdcc7000.jpg)

**Comment by xoxfaby** [comment] 2021-08-13 22:16
I don't know how this special attack works but essentially, when any attack is started, Cracked Orb will roll to see if it should create a duplicate of that attack. If this mod creates projectiles that create their own projectiles, this could obviously lead to an issue because of exponential growth.

You can find the code for all the hooks here in case it helps you to try to avoid this from happening.  

https://github.com/xoxfaby/MoreItems/blob/master/Items/CrackedOrb.cs

**Comment by TheTimeSweeper** [comment] 2024-06-08 00:23
closed as cracked orb no longer exists. problem solved!

**Closed by TheTimeSweeper** 2024-06-08 00:23 UTC
